#!/bin/bash
# Use current working directory
#$ -cwd
#
# Join stdout and stderr
#$ -j y
#
# Run job through bash shell 
#$ -S /bin/bash
#
#You can edit the scriptsince this line
#
# Your job name
#$ -N hector_vcf
#
# Send an email after the job has finished
#$ -m e
#$ -M alessandro@ciencias.unam.mx
#
# If modules are needed, source modules environment (Do not delete the next line):
. /etc/profile.d/modules.sh
#
# Add any modules you might require:
module load plink2/1.90beta3
#
# Write your commands in the next line  
plink --bfile data --alleleACGT --keep ind --recode vcf --out datos
